spring:
  datasource:
     url: jdbc:sqlserver://db-mysql-azure.database.windows.net:1433;database=mysql;user=gaurav@db-mysql-azure;password=@123mysql;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9191




